"""Build the isolated Windows AMF/D3D11/HIP resident extension out of tree.

The extension uses PyAV's private Cython declarations, so the three source
trees below are checked against the transaction's exact commits before Cython
or the C++ compiler is invoked.  Generated shader bytecode, Cython C++, object
files, and the final ``.pyd`` all stay below ``--output-dir``.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import shutil
import subprocess
import time
from pathlib import Path

from Cython.Build import cythonize
from setuptools import Distribution, Extension


PYAV_COMMIT = "7e3d950a8b72062502c1a60d672f8ca565313af5"
FFMPEG_COMMIT = "44d082edc87381d978e8588b148116b99fefdb43"
AMF_COMMIT = "c35f613aea2e5057a688c979e75b1cf24253297e"
FFMPEG_PATCHED_FILE_SHA256 = {
    "configure": "aba244a141690363fcc2cc5e027af1b7aac74d00a05ae784dc23a4856c585c3c",
    "libavcodec/amfdec.c": "b66851768b04f3f013f4fe07aa635706a7796aefc6eb95f4ee99463bbaea2d78",
    "libavformat/matroskaenc.c": "f2372b6caad6caeb47bce32c83675b20d8dc6d25fe33fc64f954e28213619e9d",
    "libavutil/hwcontext_amf.c": "de07865de2266a225a8d7c5906e5cfe037f2964e7e0a541326e158f118555fb2",
}

_COPY_HLSL = r"""
Texture2D<float4> inputTexture : register(t0);

struct VOut {
    float4 pos : SV_POSITION;
};

VOut VSMain(uint vertexId : SV_VertexID) {
    const float2 p[3] = {
        float2(-1.0, -1.0),
        float2(-1.0, 3.0),
        float2(3.0, -1.0),
    };
    VOut output;
    output.pos = float4(p[vertexId], 0.0, 1.0);
    return output;
}

float4 PSMain(VOut input) : SV_TARGET {
    return inputTexture.Load(int3(uint2(input.pos.xy), 0));
}
""".strip()


def _git_stdout(root: Path, *args: str) -> str:
    completed = subprocess.run(
        ["git", "-C", str(root), *args],
        check=True,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    return completed.stdout.strip()


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _require_pinned_source(
    root: Path,
    expected_commit: str,
    label: str,
    *,
    expected_tracked_sha256: dict[str, str] | None = None,
) -> None:
    if not root.is_dir():
        raise RuntimeError(f"{label} source directory does not exist: {root}")
    try:
        actual_commit = _git_stdout(root, "rev-parse", "HEAD")
        unstaged = _git_stdout(root, "diff", "--name-only")
        staged = _git_stdout(root, "diff", "--cached", "--name-only")
    except (OSError, subprocess.CalledProcessError) as exc:
        raise RuntimeError(f"Cannot verify the pinned {label} source at {root}") from exc
    if actual_commit != expected_commit:
        raise RuntimeError(
            f"{label} commit mismatch: expected {expected_commit}, observed {actual_commit}"
        )
    if staged:
        raise RuntimeError(f"{label} source has staged modifications: {staged}")
    changed = set(unstaged.splitlines()) if unstaged else set()
    expected_changes = set(expected_tracked_sha256 or {})
    if changed != expected_changes:
        raise RuntimeError(
            f"{label} tracked modifications differ from the accepted set: "
            f"expected {sorted(expected_changes)}, observed {sorted(changed)}"
        )
    for relative, expected_digest in (expected_tracked_sha256 or {}).items():
        path = root / relative
        actual_digest = _sha256(path) if path.is_file() else None
        if actual_digest != expected_digest:
            raise RuntimeError(
                f"{label} patched source mismatch for {relative}: expected "
                f"{expected_digest}, observed {actual_digest}"
            )


def _write_dxbc_header(path: Path, symbol: str, payload: bytes) -> None:
    if not payload:
        raise RuntimeError(f"FXC produced an empty shader blob for {symbol}")
    rows = []
    for offset in range(0, len(payload), 12):
        row = ", ".join(f"0x{byte:02x}" for byte in payload[offset : offset + 12])
        rows.append(f"    {row},")
    path.write_text(
        "#pragma once\n"
        "// Generated by build_amf_d3d11_hip_resident.py; do not edit.\n"
        f"inline constexpr unsigned char {symbol}[] = {{\n"
        + "\n".join(rows)
        + "\n};\n",
        encoding="ascii",
        newline="\n",
    )


def _resolve_fxc(value: str | None) -> Path:
    candidate = Path(value).expanduser() if value else None
    if candidate is None:
        located = shutil.which("fxc.exe") or shutil.which("fxc")
        candidate = Path(located) if located else None
    if candidate is None or not candidate.is_file():
        raise RuntimeError(
            "fxc.exe is required to precompile resident DXBC; pass --fxc or add it to PATH"
        )
    return candidate.resolve()


def _generate_dxbc_headers(fxc: Path, shader_dir: Path) -> None:
    shader_dir.mkdir(parents=True, exist_ok=True)
    hlsl = shader_dir / "amf_d3d11_hip_resident_copy.hlsl"
    hlsl.write_text(_COPY_HLSL + "\n", encoding="utf-8", newline="\n")
    for stage, entry, target, symbol in (
        ("vs", "VSMain", "vs_5_0", "jasna_amf_d3d11_hip_resident_vs"),
        ("ps", "PSMain", "ps_5_0", "jasna_amf_d3d11_hip_resident_ps"),
    ):
        blob = shader_dir / f"amf_d3d11_hip_resident_{stage}.cso"
        subprocess.run(
            [
                str(fxc),
                "/nologo",
                "/Ges",
                "/T",
                target,
                "/E",
                entry,
                "/Fo",
                str(blob),
                str(hlsl),
            ],
            check=True,
            cwd=shader_dir,
        )
        _write_dxbc_header(
            shader_dir / f"amf_d3d11_hip_resident_{stage}.hpp",
            symbol,
            blob.read_bytes(),
        )


def _existing_directory(value: str, argument: str) -> Path:
    path = Path(value).expanduser().resolve()
    if not path.is_dir():
        raise RuntimeError(f"{argument} is not a directory: {path}")
    return path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pyav-source", required=True)
    parser.add_argument("--ffmpeg-source", required=True)
    parser.add_argument("--amf-source", required=True)
    parser.add_argument("--ffmpeg-include", required=True)
    parser.add_argument("--ffmpeg-lib", required=True)
    parser.add_argument("--rocm-include", required=True)
    parser.add_argument("--rocm-lib", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--fxc")
    parser.add_argument(
        "--vctip",
        help="Optional MSVC vctip.exe to prelaunch with upload disabled",
    )
    parser.add_argument(
        "--parallel",
        type=int,
        default=2,
        help="Maximum compiler jobs (clamped to the resident build limit of 2)",
    )
    args = parser.parse_args()

    source = Path(__file__).with_name("amf_d3d11_hip_resident.pyx").resolve()
    source_dir = source.parent
    pyav_source = _existing_directory(args.pyav_source, "--pyav-source")
    ffmpeg_source = _existing_directory(args.ffmpeg_source, "--ffmpeg-source")
    amf_source = _existing_directory(args.amf_source, "--amf-source")
    ffmpeg_include = _existing_directory(args.ffmpeg_include, "--ffmpeg-include")
    ffmpeg_lib = _existing_directory(args.ffmpeg_lib, "--ffmpeg-lib")
    rocm_include = _existing_directory(args.rocm_include, "--rocm-include")
    rocm_lib = _existing_directory(args.rocm_lib, "--rocm-lib")
    amf_include = amf_source / "amf" / "public" / "include"
    if not amf_include.is_dir():
        raise RuntimeError(f"Pinned AMF include directory does not exist: {amf_include}")

    _require_pinned_source(pyav_source, PYAV_COMMIT, "PyAV")
    _require_pinned_source(
        ffmpeg_source,
        FFMPEG_COMMIT,
        "FFmpeg",
        expected_tracked_sha256=FFMPEG_PATCHED_FILE_SHA256,
    )
    _require_pinned_source(amf_source, AMF_COMMIT, "AMF")

    output = Path(args.output_dir).expanduser().resolve()
    source_tree = source_dir.parent
    if output == source_tree or output.is_relative_to(source_tree):
        raise RuntimeError(
            "--output-dir must be outside the source tree so generated DXBC, "
            "Cython C++, objects, and the module are never written into it"
        )
    output.mkdir(parents=True, exist_ok=True)
    build_root = output / "build-amf-d3d11-hip-resident"
    shader_dir = build_root / "dxbc"
    cython_dir = build_root / "cython"
    object_dir = build_root / "objects"
    amf_namespace_include = build_root / "amf-include"
    shutil.copytree(
        amf_include,
        amf_namespace_include / "AMF",
        dirs_exist_ok=True,
    )
    fxc = _resolve_fxc(args.fxc)
    vctip = Path(args.vctip).expanduser().resolve() if args.vctip else None
    if vctip is not None and not vctip.is_file():
        raise RuntimeError(f"vctip.exe does not exist: {vctip}")
    _generate_dxbc_headers(fxc, shader_dir)

    parallel = max(1, min(2, int(args.parallel)))
    # A relative source path prevents distutils from reproducing the full
    # absolute drive path below build_temp, which otherwise exceeds the Win32
    # compiler's generated-file path limit. This is a standalone build entry
    # point, so selecting the pinned repository root as its process cwd is
    # intentional.
    os.chdir(source_tree)
    extension = Extension(
        "_jasna_amf_d3d11_hip_resident",
        [str(source.relative_to(source_tree))],
        define_macros=[
            ("__HIP_PLATFORM_AMD__", "1"),
            ("WIN32_LEAN_AND_MEAN", "1"),
            ("NOMINMAX", "1"),
        ],
        include_dirs=[
            str(source_dir),
            str(shader_dir),
            str(pyav_source / "include"),
            str(pyav_source),
            str(amf_namespace_include),
            str(ffmpeg_include),
            str(rocm_include),
        ],
        library_dirs=[str(ffmpeg_lib), str(rocm_lib)],
        libraries=[
            "avcodec",
            "avutil",
            "d3d11",
            "d3d12",
            "dxgi",
            "amdhip64",
            "delayimp",
            "uuid",
        ],
        language="c++",
        extra_compile_args=["/std:c++17", "/EHsc"],
        extra_link_args=["/DELAYLOAD:amdhip64_7.dll"],
    )
    cythonized_extensions = cythonize(
        [extension],
        compiler_directives={"language_level": "3"},
        build_dir=str(cython_dir),
        include_path=[str(pyav_source / "include"), str(pyav_source)],
    )
    # Cython returns an absolute generated .cpp path. Distutils otherwise
    # mirrors that entire drive path below build_temp and can still exceed the
    # MSVC /Fo limit. Build from the external build root with generated sources
    # rewritten relative to it.
    for cythonized in cythonized_extensions:
        relative_sources: list[str] = []
        for generated in cythonized.sources:
            generated_path = Path(generated)
            if not generated_path.is_absolute():
                generated_path = (source_tree / generated_path).resolve()
            relative_sources.append(str(generated_path.relative_to(build_root)))
        cythonized.sources = relative_sources
    os.chdir(build_root)
    distribution = Distribution(
        {
            "name": "jasna-amf-d3d11-hip-resident",
            "ext_modules": cythonized_extensions,
        }
    )
    command = distribution.get_command_obj("build_ext")
    command.build_lib = str(output)
    command.build_temp = str(object_dir)
    command.inplace = False
    command.parallel = parallel
    vctip_process: subprocess.Popen[bytes] | None = None
    if vctip is not None:
        creationflags = getattr(subprocess, "CREATE_NO_WINDOW", 0)
        vctip_process = subprocess.Popen(
            [str(vctip), "-upload:skip", "-timeout:5"],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            creationflags=creationflags,
        )
        time.sleep(0.5)
        if vctip_process.poll() is not None:
            raise RuntimeError(
                "contained VCTIP upload-skipping server exited before compilation"
            )
    try:
        distribution.run_command("build_ext")
    finally:
        if vctip_process is not None:
            try:
                vctip_process.wait(timeout=10)
            except subprocess.TimeoutExpired:
                vctip_process.terminate()
                vctip_process.wait(timeout=5)
                raise RuntimeError(
                    "contained VCTIP upload-skipping server exceeded its idle timeout"
                )
            if vctip_process.returncode != 0:
                raise RuntimeError(
                    "contained VCTIP upload-skipping server failed with exit "
                    f"code {vctip_process.returncode}"
                )

    modules = sorted(output.glob("_jasna_amf_d3d11_hip_resident*.pyd"))
    if not modules:
        raise RuntimeError("resident extension build produced no .pyd module")
    print(modules[-1])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
