"""Regenerate jasna/ltx/trial_shapes.py from local LTX model files (dev only).

Reads only the safetensors headers: tensor names, shapes and dtypes, the VAE architecture
config, and each transformer's step count and whether it uses STG. Weights, the sigma
schedule and the license text are not copied.

    python scripts/ltx_trial_shapes.py [model_weights/ltx-restore]
"""

import json
import struct
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from jasna.ltx.model_files import LTX_MODELS, bundle_names  # noqa: E402

OUTPUT = REPO / "jasna" / "ltx" / "trial_shapes.py"


def read_header(path: Path) -> tuple[dict[str, tuple[str, tuple[int, ...]]], dict[str, str]]:
    with path.open("rb") as handle:
        size = struct.unpack("<Q", handle.read(8))[0]
        header = json.loads(handle.read(size))
    metadata = header.pop("__metadata__", {})
    return {name: (entry["dtype"], tuple(entry["shape"])) for name, entry in sorted(header.items())}, metadata


def split_blocks(tensors: dict) -> tuple[int, dict, dict]:
    top = {name: spec for name, spec in tensors.items() if not name.startswith("blocks.")}
    blocks: dict[int, dict] = {}
    for name, spec in tensors.items():
        if name.startswith("blocks."):
            _, index, rest = name.split(".", 2)
            blocks.setdefault(int(index), {})[rest] = spec
    first = blocks[0]
    if sorted(blocks) != list(range(len(blocks))) or any(block != first for block in blocks.values()):
        raise ValueError("transformer blocks differ; the trial assumes identical blocks")
    return len(blocks), top, first


def main() -> None:
    directory = Path(sys.argv[1]) if len(sys.argv) > 1 else REPO / "model_weights" / "ltx-restore"
    transformer: dict[str, tuple[dict, dict]] = {}
    steps: dict[str, tuple[int, bool]] = {}
    block_count = None
    for model in LTX_MODELS:
        for fast, precision in ((False, "int8"), (True, "nvfp4")):
            tensors, metadata = read_header(directory / bundle_names(model, fast=fast)[0])
            count, top, block = split_blocks(tensors)
            if transformer.setdefault(precision, (top, block)) != (top, block) or block_count not in (None, count):
                raise ValueError(f"{model} {precision}: shapes differ from the other model")
            block_count = count
            sampler = (len(json.loads(metadata["sigmas"])) - 1, float(metadata["stg_scale"]) > 0)
            if steps.setdefault(model, sampler) != sampler:
                raise ValueError(f"{model}: int8 and nvfp4 sample differently")
    _, vae_name, decoder_name = bundle_names(LTX_MODELS[0], fast=False)
    vae, vae_metadata = read_header(directory / vae_name)
    decoder, _ = read_header(directory / decoder_name)

    lines = [
        '"""Tensor names, shapes and dtypes of the LTX model files, for the trial\'s placeholder',
        "weights. Generated by scripts/ltx_trial_shapes.py; architecture only, no weights.\"\"\"",
        "",
        f"BLOCKS = {block_count}",
        "",
        "# model -> (sampler steps, uses STG)",
        f"STEPS = {steps!r}",
        "",
        f"VAE_CONFIG = {json.loads(vae_metadata['config'])!r}",
        "",
        "TRANSFORMER = {",
    ]
    for precision, (top, block) in transformer.items():
        lines.append(f"    {precision!r}: {{")
        for part, specs in (("top", top), ("block", block)):
            lines.append(f"        {part!r}: {{")
            lines += [f"            {name!r}: {spec!r}," for name, spec in specs.items()]
            lines.append("        },")
        lines.append("    },")
    lines.append("}")
    for name, specs in (("VAE", vae), ("VAE_DECODER", decoder)):
        lines += ["", f"{name} = {{"]
        lines += [f"    {tensor!r}: {spec!r}," for tensor, spec in specs.items()]
        lines.append("}")
    OUTPUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
